---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Copier la configuration Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Redémarrer Nginx
  become: true

- name: Copier la page d'accueil
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: Assurer que Nginx est démarré
  service:
    name: nginx
    state: started
    enabled: true
  become: true
